### ISSUE TITLE
Hide/Show correct elements for Winner

### ISSUE THREAD

**Issue by angelicamapeso** [Mark-Quirante/pokemon-battle#9]
**Acceptance Criteria**
Winner screen should look similar to:
![image](https://github.com/user-attachments/assets/42ed9423-25c8-4fbc-aa96-114322d0b534)

The hidden elements are:

- Loser Pokemon
- Loser Stats

The shown elements are:

- Winner box with the name of the winner in it

**Comment by markquirante** [comment]
I'm on it!

**Comment by markquirante** [comment]
Hey! I managed to get most of the work done. However I have a slight issue/bug.

![Screenshot 2024-07-15 140303](https://github.com/user-attachments/assets/a84f6e32-9e75-446e-8d5d-4549ea44e413)

- Loser Pokemon Platform is also hidden

I will work on it later! Let me know if you have ideas on how to fix this.

Thank you!

**Comment by angelicamapeso** [comment]
Fixed!
